version: '3'

services:
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: db
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.4-bionic
    ports:
      - 27017:27017
