version: '3'

services:
  worker-challenge2021:
    container_name: worker-challenge2021
    build:
      context: .
    depends_on:
      - mongo-challenge2021

  mongo-challenge2021:
    container_name: mongo-challenge2021
    image: mongo:4.4-bionic
    ports:
      - 27017:27017
